/* ============================================================
   Datos JLPT N5 — Kanji y Verbos
   Verbos: solo guardamos forma de diccionario, lectura, tipo y
   significado. Las formas ます y て se calculan en app.js.
   tipo: "godan" | "ichidan" | "irregular"
   exc:  "iku" marca la excepción 行く (て irregular)
   ============================================================ */

const KANJI = [
  { k: "一", on: "イチ", kun: "ひと(つ)", m: "uno" },
  { k: "二", on: "ニ", kun: "ふた(つ)", m: "dos" },
  { k: "三", on: "サン", kun: "みっ(つ)", m: "tres" },
  { k: "四", on: "シ", kun: "よっ(つ)・よん", m: "cuatro" },
  { k: "五", on: "ゴ", kun: "いつ(つ)", m: "cinco" },
  { k: "六", on: "ロク", kun: "むっ(つ)", m: "seis" },
  { k: "七", on: "シチ", kun: "なな(つ)", m: "siete" },
  { k: "八", on: "ハチ", kun: "やっ(つ)", m: "ocho" },
  { k: "九", on: "キュウ・ク", kun: "ここの(つ)", m: "nueve" },
  { k: "十", on: "ジュウ", kun: "とお", m: "diez" },
  { k: "百", on: "ヒャク", kun: "—", m: "cien" },
  { k: "千", on: "セン", kun: "ち", m: "mil" },
  { k: "万", on: "マン・バン", kun: "—", m: "diez mil" },
  { k: "円", on: "エン", kun: "まる(い)", m: "yen / círculo" },
  { k: "日", on: "ニチ・ジツ", kun: "ひ・か", m: "día / sol" },
  { k: "月", on: "ゲツ・ガツ", kun: "つき", m: "mes / luna" },
  { k: "火", on: "カ", kun: "ひ", m: "fuego" },
  { k: "水", on: "スイ", kun: "みず", m: "agua" },
  { k: "木", on: "ボク・モク", kun: "き", m: "árbol / madera" },
  { k: "金", on: "キン・コン", kun: "かね", m: "oro / dinero" },
  { k: "土", on: "ド・ト", kun: "つち", m: "tierra / suelo" },
  { k: "曜", on: "ヨウ", kun: "—", m: "día de la semana" },
  { k: "本", on: "ホン", kun: "もと", m: "libro / origen" },
  { k: "人", on: "ジン・ニン", kun: "ひと", m: "persona" },
  { k: "年", on: "ネン", kun: "とし", m: "año" },
  { k: "時", on: "ジ", kun: "とき", m: "hora / tiempo" },
  { k: "分", on: "ブン・フン", kun: "わ(かる)・わ(ける)", m: "minuto / parte" },
  { k: "間", on: "カン・ケン", kun: "あいだ・ま", m: "intervalo / entre" },
  { k: "今", on: "コン", kun: "いま", m: "ahora" },
  { k: "午", on: "ゴ", kun: "—", m: "mediodía" },
  { k: "前", on: "ゼン", kun: "まえ", m: "antes / delante" },
  { k: "後", on: "ゴ・コウ", kun: "うし(ろ)・あと", m: "después / detrás" },
  { k: "半", on: "ハン", kun: "なか(ば)", m: "mitad" },
  { k: "週", on: "シュウ", kun: "—", m: "semana" },
  { k: "毎", on: "マイ", kun: "—", m: "cada" },
  { k: "何", on: "カ", kun: "なに・なん", m: "qué / cuánto" },
  { k: "名", on: "メイ・ミョウ", kun: "な", m: "nombre" },
  { k: "先", on: "セン", kun: "さき", m: "anterior / punta" },
  { k: "生", on: "セイ・ショウ", kun: "い(きる)・う(まれる)", m: "vida / nacer" },
  { k: "学", on: "ガク", kun: "まな(ぶ)", m: "estudio / aprender" },
  { k: "校", on: "コウ", kun: "—", m: "escuela" },
  { k: "語", on: "ゴ", kun: "かた(る)", m: "idioma / palabra" },
  { k: "国", on: "コク", kun: "くに", m: "país" },
  { k: "中", on: "チュウ", kun: "なか", m: "centro / dentro" },
  { k: "外", on: "ガイ・ゲ", kun: "そと・ほか", m: "afuera / exterior" },
  { k: "上", on: "ジョウ", kun: "うえ・あ(がる)", m: "arriba / encima" },
  { k: "下", on: "カ・ゲ", kun: "した・さ(がる)", m: "abajo / debajo" },
  { k: "左", on: "サ", kun: "ひだり", m: "izquierda" },
  { k: "右", on: "ウ・ユウ", kun: "みぎ", m: "derecha" },
  { k: "東", on: "トウ", kun: "ひがし", m: "este (dirección)" },
  { k: "西", on: "セイ・サイ", kun: "にし", m: "oeste" },
  { k: "南", on: "ナン", kun: "みなみ", m: "sur" },
  { k: "北", on: "ホク", kun: "きた", m: "norte" },
  { k: "口", on: "コウ", kun: "くち", m: "boca" },
  { k: "目", on: "モク", kun: "め", m: "ojo" },
  { k: "耳", on: "ジ", kun: "みみ", m: "oreja" },
  { k: "手", on: "シュ", kun: "て", m: "mano" },
  { k: "足", on: "ソク", kun: "あし・た(りる)", m: "pie / pierna / bastar" },
  { k: "大", on: "ダイ・タイ", kun: "おお(きい)", m: "grande" },
  { k: "小", on: "ショウ", kun: "ちい(さい)・こ", m: "pequeño" },
  { k: "高", on: "コウ", kun: "たか(い)", m: "alto / caro" },
  { k: "安", on: "アン", kun: "やす(い)", m: "barato / tranquilo" },
  { k: "新", on: "シン", kun: "あたら(しい)", m: "nuevo" },
  { k: "古", on: "コ", kun: "ふる(い)", m: "viejo / usado" },
  { k: "長", on: "チョウ", kun: "なが(い)", m: "largo / jefe" },
  { k: "白", on: "ハク", kun: "しろ(い)", m: "blanco" },
  { k: "山", on: "サン", kun: "やま", m: "montaña" },
  { k: "川", on: "セン", kun: "かわ", m: "río" },
  { k: "田", on: "デン", kun: "た", m: "campo de arroz" },
  { k: "天", on: "テン", kun: "あま", m: "cielo" },
  { k: "気", on: "キ・ケ", kun: "—", m: "ánimo / aire / energía" },
  { k: "雨", on: "ウ", kun: "あめ", m: "lluvia" },
  { k: "電", on: "デン", kun: "—", m: "electricidad" },
  { k: "車", on: "シャ", kun: "くるま", m: "coche / vehículo" },
  { k: "駅", on: "エキ", kun: "—", m: "estación (tren)" },
  { k: "社", on: "シャ", kun: "やしろ", m: "empresa / santuario" },
  { k: "店", on: "テン", kun: "みせ", m: "tienda" },
  { k: "道", on: "ドウ", kun: "みち", m: "camino / calle" },
  { k: "食", on: "ショク", kun: "た(べる)・く(う)", m: "comer / comida" },
  { k: "飲", on: "イン", kun: "の(む)", m: "beber" },
  { k: "見", on: "ケン", kun: "み(る)", m: "ver / mirar" },
  { k: "聞", on: "ブン・モン", kun: "き(く)", m: "oír / preguntar" },
  { k: "言", on: "ゲン・ゴン", kun: "い(う)・こと", m: "decir / palabra" },
  { k: "話", on: "ワ", kun: "はな(す)・はなし", m: "hablar / historia" },
  { k: "読", on: "ドク", kun: "よ(む)", m: "leer" },
  { k: "書", on: "ショ", kun: "か(く)", m: "escribir" },
  { k: "行", on: "コウ・ギョウ", kun: "い(く)・おこな(う)", m: "ir / realizar" },
  { k: "来", on: "ライ", kun: "く(る)・き", m: "venir" },
  { k: "出", on: "シュツ", kun: "で(る)・だ(す)", m: "salir / sacar" },
  { k: "入", on: "ニュウ", kun: "はい(る)・い(れる)", m: "entrar / meter" },
  { k: "立", on: "リツ", kun: "た(つ)", m: "pararse / estar de pie" },
  { k: "休", on: "キュウ", kun: "やす(む)", m: "descansar" },
  { k: "買", on: "バイ", kun: "か(う)", m: "comprar" },
  { k: "父", on: "フ", kun: "ちち・とう", m: "padre" },
  { k: "母", on: "ボ", kun: "はは・かあ", m: "madre" },
  { k: "友", on: "ユウ", kun: "とも", m: "amigo" },
  { k: "男", on: "ダン・ナン", kun: "おとこ", m: "hombre" },
  { k: "女", on: "ジョ・ニョ", kun: "おんな・め", m: "mujer" },
  { k: "子", on: "シ・ス", kun: "こ", m: "niño / hijo" },
  { k: "花", on: "カ", kun: "はな", m: "flor" },
  { k: "空", on: "クウ", kun: "そら・あ(く)", m: "cielo / vacío" },
];

const VERBS = [
  { k: "食べる", r: "たべる", type: "ichidan", m: "comer" },
  { k: "飲む", r: "のむ", type: "godan", m: "beber" },
  { k: "行く", r: "いく", type: "godan", exc: "iku", m: "ir" },
  { k: "来る", r: "くる", type: "irregular", m: "venir" },
  { k: "する", r: "する", type: "irregular", m: "hacer" },
  { k: "勉強する", r: "べんきょうする", type: "irregular", m: "estudiar" },
  { k: "見る", r: "みる", type: "ichidan", m: "ver / mirar" },
  { k: "聞く", r: "きく", type: "godan", m: "oír / preguntar" },
  { k: "話す", r: "はなす", type: "godan", m: "hablar" },
  { k: "書く", r: "かく", type: "godan", m: "escribir" },
  { k: "読む", r: "よむ", type: "godan", m: "leer" },
  { k: "買う", r: "かう", type: "godan", m: "comprar" },
  { k: "起きる", r: "おきる", type: "ichidan", m: "levantarse / despertarse" },
  { k: "寝る", r: "ねる", type: "ichidan", m: "dormir / acostarse" },
  { k: "帰る", r: "かえる", type: "godan", m: "regresar a casa" },
  { k: "待つ", r: "まつ", type: "godan", m: "esperar" },
  { k: "使う", r: "つかう", type: "godan", m: "usar" },
  { k: "分かる", r: "わかる", type: "godan", m: "entender" },
  { k: "入る", r: "はいる", type: "godan", m: "entrar" },
  { k: "出る", r: "でる", type: "ichidan", m: "salir" },
  { k: "会う", r: "あう", type: "godan", m: "encontrarse / reunirse" },
  { k: "作る", r: "つくる", type: "godan", m: "hacer / crear" },
  { k: "立つ", r: "たつ", type: "godan", m: "pararse" },
  { k: "休む", r: "やすむ", type: "godan", m: "descansar" },
  { k: "泳ぐ", r: "およぐ", type: "godan", m: "nadar" },
  { k: "遊ぶ", r: "あそぶ", type: "godan", m: "jugar / divertirse" },
  { k: "死ぬ", r: "しぬ", type: "godan", m: "morir" },
  { k: "住む", r: "すむ", type: "godan", m: "vivir / residir" },
  { k: "言う", r: "いう", type: "godan", m: "decir" },
  { k: "思う", r: "おもう", type: "godan", m: "pensar / creer" },
  { k: "持つ", r: "もつ", type: "godan", m: "tener / sostener" },
  { k: "取る", r: "とる", type: "godan", m: "tomar / coger" },
  { k: "撮る", r: "とる", type: "godan", m: "tomar (foto)" },
  { k: "売る", r: "うる", type: "godan", m: "vender" },
  { k: "知る", r: "しる", type: "godan", m: "saber / conocer" },
  { k: "走る", r: "はしる", type: "godan", m: "correr" },
  { k: "切る", r: "きる", type: "godan", m: "cortar" },
  { k: "要る", r: "いる", type: "godan", m: "necesitar" },
  { k: "乗る", r: "のる", type: "godan", m: "subirse / montar" },
  { k: "降る", r: "ふる", type: "godan", m: "caer (lluvia/nieve)" },
  { k: "登る", r: "のぼる", type: "godan", m: "subir / escalar" },
  { k: "歩く", r: "あるく", type: "godan", m: "caminar" },
  { k: "着く", r: "つく", type: "godan", m: "llegar" },
  { k: "着る", r: "きる", type: "ichidan", m: "ponerse (ropa)" },
  { k: "教える", r: "おしえる", type: "ichidan", m: "enseñar" },
  { k: "覚える", r: "おぼえる", type: "ichidan", m: "recordar / memorizar" },
  { k: "忘れる", r: "わすれる", type: "ichidan", m: "olvidar" },
  { k: "借りる", r: "かりる", type: "ichidan", m: "pedir prestado" },
  { k: "開ける", r: "あける", type: "ichidan", m: "abrir (algo)" },
  { k: "閉める", r: "しめる", type: "ichidan", m: "cerrar (algo)" },
  { k: "開く", r: "あく", type: "godan", m: "abrirse" },
  { k: "始める", r: "はじめる", type: "ichidan", m: "empezar (algo)" },
  { k: "始まる", r: "はじまる", type: "godan", m: "empezar (intransitivo)" },
  { k: "止まる", r: "とまる", type: "godan", m: "detenerse" },
  { k: "消す", r: "けす", type: "godan", m: "apagar / borrar" },
  { k: "つける", r: "つける", type: "ichidan", m: "encender" },
  { k: "かける", r: "かける", type: "ichidan", m: "colgar / llamar (teléfono)" },
  { k: "答える", r: "こたえる", type: "ichidan", m: "responder" },
  { k: "考える", r: "かんがえる", type: "ichidan", m: "pensar / considerar" },
  { k: "生まれる", r: "うまれる", type: "ichidan", m: "nacer" },
  { k: "出かける", r: "でかける", type: "ichidan", m: "salir (a hacer algo)" },
  { k: "浴びる", r: "あびる", type: "ichidan", m: "ducharse / bañarse" },
  { k: "見せる", r: "みせる", type: "ichidan", m: "mostrar" },
  { k: "貸す", r: "かす", type: "godan", m: "prestar" },
  { k: "返す", r: "かえす", type: "godan", m: "devolver" },
  { k: "渡す", r: "わたす", type: "godan", m: "entregar / pasar" },
  { k: "渡る", r: "わたる", type: "godan", m: "cruzar" },
  { k: "歌う", r: "うたう", type: "godan", m: "cantar" },
  { k: "習う", r: "ならう", type: "godan", m: "aprender (de un maestro)" },
  { k: "洗う", r: "あらう", type: "godan", m: "lavar" },
  { k: "吸う", r: "すう", type: "godan", m: "fumar / aspirar" },
  { k: "押す", r: "おす", type: "godan", m: "empujar / presionar" },
  { k: "引く", r: "ひく", type: "godan", m: "tirar / jalar" },
  { k: "弾く", r: "ひく", type: "godan", m: "tocar (instrumento)" },
  { k: "飛ぶ", r: "とぶ", type: "godan", m: "volar" },
  { k: "運ぶ", r: "はこぶ", type: "godan", m: "transportar / llevar" },
  { k: "喜ぶ", r: "よろこぶ", type: "godan", m: "alegrarse" },
  { k: "選ぶ", r: "えらぶ", type: "godan", m: "elegir" },
  { k: "呼ぶ", r: "よぶ", type: "godan", m: "llamar" },
  { k: "並ぶ", r: "ならぶ", type: "godan", m: "alinearse / hacer fila" },
  { k: "並べる", r: "ならべる", type: "ichidan", m: "ordenar / alinear" },
  { k: "曲がる", r: "まがる", type: "godan", m: "doblar / girar" },
  { k: "困る", r: "こまる", type: "godan", m: "tener problemas" },
  { k: "座る", r: "すわる", type: "godan", m: "sentarse" },
  { k: "笑う", r: "わらう", type: "godan", m: "reír" },
  { k: "泣く", r: "なく", type: "godan", m: "llorar" },
  { k: "咲く", r: "さく", type: "godan", m: "florecer" },
  { k: "飼う", r: "かう", type: "godan", m: "criar (mascota)" },
  { k: "晴れる", r: "はれる", type: "ichidan", m: "despejarse (clima)" },
  { k: "曇る", r: "くもる", type: "godan", m: "nublarse" },
  { k: "疲れる", r: "つかれる", type: "ichidan", m: "cansarse" },
  { k: "やる", r: "やる", type: "godan", m: "hacer / dar" },
  { k: "もらう", r: "もらう", type: "godan", m: "recibir" },
  { k: "あげる", r: "あげる", type: "ichidan", m: "dar (a otro)" },
  { k: "くれる", r: "くれる", type: "ichidan", m: "dar (a mí)" },
  { k: "できる", r: "できる", type: "ichidan", m: "poder / ser capaz" },
  { k: "落ちる", r: "おちる", type: "ichidan", m: "caer(se)" },
  { k: "決める", r: "きめる", type: "ichidan", m: "decidir" },
  { k: "止める", r: "とめる", type: "ichidan", m: "detener / parar (algo)" },
];

/* ============================================================
   Adjetivos N5
   type: "i" (adjetivos-い) | "na" (adjetivos-な)
   exc: "ii" marca la excepción いい (conjugación: よ-)
   ============================================================ */
const ADJECTIVES = [
  // ---- い adjectives ----
  { k: "大きい",     r: "おおきい",   m: "grande",                     type: "i" },
  { k: "小さい",     r: "ちいさい",   m: "pequeño",                    type: "i" },
  { k: "高い",       r: "たかい",     m: "alto / caro",                type: "i" },
  { k: "安い",       r: "やすい",     m: "barato",                     type: "i" },
  { k: "新しい",     r: "あたらしい", m: "nuevo",                      type: "i" },
  { k: "古い",       r: "ふるい",     m: "viejo",                      type: "i" },
  { k: "長い",       r: "ながい",     m: "largo",                      type: "i" },
  { k: "短い",       r: "みじかい",   m: "corto",                      type: "i" },
  { k: "広い",       r: "ひろい",     m: "amplio / espacioso",         type: "i" },
  { k: "狭い",       r: "せまい",     m: "angosto / estrecho",         type: "i" },
  { k: "多い",       r: "おおい",     m: "mucho / muchos",             type: "i" },
  { k: "少ない",     r: "すくない",   m: "poco / pocos",               type: "i" },
  { k: "難しい",     r: "むずかしい", m: "difícil",                    type: "i" },
  { k: "易しい",     r: "やさしい",   m: "fácil",                      type: "i" },
  { k: "面白い",     r: "おもしろい", m: "interesante / divertido",    type: "i" },
  { k: "つまらない", r: "つまらない", m: "aburrido",                   type: "i" },
  { k: "楽しい",     r: "たのしい",   m: "divertido / agradable",      type: "i" },
  { k: "悲しい",     r: "かなしい",   m: "triste",                     type: "i" },
  { k: "嬉しい",     r: "うれしい",   m: "alegre / feliz",             type: "i" },
  { k: "怖い",       r: "こわい",     m: "aterrador / da miedo",       type: "i" },
  { k: "痛い",       r: "いたい",     m: "doloroso",                   type: "i" },
  { k: "暑い",       r: "あつい",     m: "caluroso (clima)",           type: "i" },
  { k: "寒い",       r: "さむい",     m: "frío (clima)",               type: "i" },
  { k: "熱い",       r: "あつい",     m: "caliente (al tacto)",        type: "i" },
  { k: "冷たい",     r: "つめたい",   m: "frío (al tacto)",            type: "i" },
  { k: "白い",       r: "しろい",     m: "blanco",                     type: "i" },
  { k: "黒い",       r: "くろい",     m: "negro",                      type: "i" },
  { k: "赤い",       r: "あかい",     m: "rojo",                       type: "i" },
  { k: "青い",       r: "あおい",     m: "azul / verde",               type: "i" },
  { k: "黄色い",     r: "きいろい",   m: "amarillo",                   type: "i" },
  { k: "いい",       r: "いい",       m: "bueno",                      type: "i", exc: "ii" },
  { k: "悪い",       r: "わるい",     m: "malo",                       type: "i" },
  { k: "早い",       r: "はやい",     m: "temprano / rápido",          type: "i" },
  { k: "遅い",       r: "おそい",     m: "tarde / lento",              type: "i" },
  { k: "重い",       r: "おもい",     m: "pesado",                     type: "i" },
  { k: "軽い",       r: "かるい",     m: "ligero",                     type: "i" },
  { k: "甘い",       r: "あまい",     m: "dulce",                      type: "i" },
  { k: "辛い",       r: "からい",     m: "picante",                    type: "i" },
  { k: "若い",       r: "わかい",     m: "joven",                      type: "i" },
  { k: "忙しい",     r: "いそがしい", m: "ocupado / atareado",         type: "i" },
  // ---- な adjectives ----
  { k: "静か",       r: "しずか",     m: "tranquilo / silencioso",     type: "na" },
  { k: "賑やか",     r: "にぎやか",   m: "animado / bullicioso",       type: "na" },
  { k: "親切",       r: "しんせつ",   m: "amable / bondadoso",         type: "na" },
  { k: "丁寧",       r: "ていねい",   m: "educado / cuidadoso",        type: "na" },
  { k: "元気",       r: "げんき",     m: "enérgico / saludable",       type: "na" },
  { k: "便利",       r: "べんり",     m: "conveniente / práctico",     type: "na" },
  { k: "不便",       r: "ふべん",     m: "inconveniente",              type: "na" },
  { k: "好き",       r: "すき",       m: "gustar / favorito",          type: "na" },
  { k: "嫌い",       r: "きらい",     m: "odiar / desagradar",         type: "na" },
  { k: "上手",       r: "じょうず",   m: "hábil / bueno en algo",      type: "na" },
  { k: "下手",       r: "へた",       m: "torpe / malo en algo",       type: "na" },
  { k: "得意",       r: "とくい",     m: "bueno en / punto fuerte",    type: "na" },
  { k: "苦手",       r: "にがて",     m: "punto débil / malo en",      type: "na" },
  { k: "有名",       r: "ゆうめい",   m: "famoso",                     type: "na" },
  { k: "大切",       r: "たいせつ",   m: "importante / precioso",      type: "na" },
  { k: "大丈夫",     r: "だいじょうぶ", m: "está bien / no hay problema", type: "na" },
  { k: "特別",       r: "とくべつ",   m: "especial",                   type: "na" },
  { k: "普通",       r: "ふつう",     m: "normal / común",             type: "na" },
  { k: "必要",       r: "ひつよう",   m: "necesario",                  type: "na" },
  { k: "大変",       r: "たいへん",   m: "difícil / terrible / muy",   type: "na" },
  { k: "暇",         r: "ひま",       m: "libre (de tiempo) / ocioso", type: "na" },
  { k: "真面目",     r: "まじめ",     m: "serio / responsable",        type: "na" },
  { k: "きれい",     r: "きれい",     m: "bonito / limpio",            type: "na" },
  { k: "いろいろ",   r: "いろいろ",   m: "variado / diverso",          type: "na" },
  { k: "大好き",     r: "だいすき",   m: "adorar / amar mucho",        type: "na" },
];
